MODEL:
  TYPE: siam_swin_22k
  PROJECTION_DIM: 256
  CONTRASTIVE_MARGIN: 1.25

TRAIN:
  WARMUP_EPOCHS: 5
  EPOCHS: 50
  BASE_LR: 0.00001 
  WEIGHT_DECAY: 0.001
  ACCUMULATION_STEPS: 1
  NUM_GPUS: 1 
  NUM_PATIENCES: 10
  
DATA:
  BATCH_SIZE: 32
  NUM_WORKERS: 16
  
AUG:
  SSL_AUG_CROP: 0.7